repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff  # linter
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      - id: ruff-format  # formatter
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.362
    hooks:
    - id: pyright
      additional_dependencies: []
      args: []
