services:
  log:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      DOZZLE_BASE: /log
    stop_grace_period: 0.5s
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:latest
    restart: unless-stopped
    stop_grace_period: 1s
    env_file:
       - '.variables.env'
    volumes:
      - postgres_data:/data

  app:
    restart: unless-stopped
    stop_grace_period: 500ms
    environment:
      PUBLIC_KERNEL_ORIGIN: http://kernel:8000
      PG_CONNECTION_STRING: postgres://user:password@postgres:5432/spectral_db
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules/
    expose:
      - "5173"
    depends_on:
      - kernel
      - postgres

  nginx:
    image: nginx:latest
    restart: unless-stopped
    stop_grace_period: 200ms
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  kernel:
    restart: unless-stopped
    stop_grace_period: 500ms
    build:
      context: ./kernel
      dockerfile: Dockerfile
    volumes:
      - ./kernel:/kernel
      - pip_cache:/kernel/.venv
    expose:
      - "8000"
    depends_on:
      - postgres
    env_file:
       - '.variables.env'
       - '.apikeys.env'

volumes:
  postgres_data:
  node_modules:
  pip_cache:

networks:
  default:
    external: false
