services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    stop_grace_period: 1s
    env_file:
       - '.variables.env'
    volumes:
      - postgres_data:/data

  frontend:
    restart: unless-stopped
    stop_grace_period: 500ms
    environment:
      PUBLIC_KERNEL_ORIGIN: http://backend
      PG_CONNECTION_STRING: postgres://user:password@postgres:5432/spectral_db
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules/      
    expose:
      - "5173"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    restart: unless-stopped
    stop_grace_period: 200ms
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend

  backend:
    restart: unless-stopped
    stop_grace_period: 500ms
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    expose:
      - "8000"
    depends_on:
      - postgres
    env_file:
       - '.variables.env'
       - '.apikeys.env'
      
volumes:
  postgres_data:

networks:
  default:
    external: false

