services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    expose:
      - "5173"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    expose:
      - "8000"
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  default:
    external: false

