FROM node:20-alpine

WORKDIR /app

COPY . .

RUN corepack enable

RUN pnpm install --prod

RUN pnpm run build

CMD BODY_SIZE_LIMIT=512000000 PORT=5173 node -r dotenv/config build | pnpm exec pino-pretty
